### ISSUE TITLE
Add tenant data table 

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#121]
You should add tenant data table by using publicgateway/swagger/index.html?urls.primaryName=Saas%20API 

The table logic could be similar to the roles table in the app which you can find in this page: 
https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/blob/f8762f6b9cbd2929131d175dc2d1a8eea4a4f5ed/apps/web/src/app/%5Blang%5D/(main)/dashboard/page.tsx 

the user should be able to do the next: 
- [ ] show all tenants 
- [ ] create new tenant 
- [ ] delete tenant 
- [ ] update an existing tenant 

You should fork this repo, create a new branch, and open a pull request from that branch.

**Comment by yusualhashash** [comment]
i am working on it
