### ISSUE TITLE
style: minor style changes

### ISSUE THREAD

**Issue by eren-ayasofyazilim** [ayasofyazilim-clomerce/ayasofyazilim-core-project#41]

**Comment by eren-odaci** [comment]
[b70192a](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/pull/42/commits/b70192a5990e02ecd9d0570d92ca5511150ab724)
[064b10e](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/pull/42/commits/064b10ed90fad6cbb2129fa577c7d4c105d72fef)
[b6694d4](https://github.com/ayasofyazilim-clomerce/ayasofyazilim-core-project/pull/42/commits/b6694d49d48633267580408d876cad09d9b31d22)
