### ISSUE TITLE
Unirefund profile menu hide extra menus.

### ISSUE THREAD

**Issue by ertugrulcan-ays** [ayasofyazilim-clomerce/ayasofyazilim-core-project#509]
![image](https://github.com/user-attachments/assets/cf08472d-3e8a-4d8d-b475-0bbe1a90b71e)

**Comment by ahmeterenodaci** [comment]
![resim](https://github.com/user-attachments/assets/8a14c156-01e3-4b2a-80af-5b3033b39897)
