### ISSUE TITLE
feat: add return URL to middleware

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#53]
If we went to an unauthorized page without login, like the `dashboard,` the user would be prompted to log in, yet after logging in, we redirect the user to the main page; it would be great if we have a return URL to redirect him to the link he was supposed to visit.

**Comment by eren-ayasofyazilim** [comment]
#301

**Comment by eren-ayasofyazilim** [comment]
#459
