### ISSUE TITLE
Feedbacks 

### ISSUE THREAD

**Issue by a0m0rajab** [ayasofyazilim-clomerce/ayasofyazilim-core-project#619]
- change all languages in forms and dialogue to match the screen language 
- add filters to all tables

**Comment by a0m0rajab** [comment]
Filter fetches

**Comment by a0m0rajab** [comment]
Alert dialog for tables (have generic method)

**Comment by a0m0rajab** [comment]
Merchant 
Sub merchant 
Reporter

**Comment by a0m0rajab** [comment]
Branch code

**Comment by a0m0rajab** [comment]
Headquarters 
Store 
Merchant 
Franchise

**Comment by a0m0rajab** [comment]
Unexpected end of json (CRM)

**Comment by a0m0rajab** [comment]
Add sub companies to data grid as sub content

**Comment by a0m0rajab** [comment]
Change view to columns (visible columns)

**Comment by a0m0rajab** [comment]
Search for menu items and data items in navigation (bookmark Ertuğrul)

**Comment by a0m0rajab** [comment]
Rebate refund scenarios showing (preview)

**Comment by a0m0rajab** [comment]
Crm do not use companies 
Show the left menu

**Comment by ertugrulcan-ays** [comment]
always visible action buttons in forms
multiple phone and address merchant
traveller search with query list
create contract as edit contract ptf
refunt settings,reebate settings,invocing settings,store?(contract create)
contract create on CRM pages
move templates to management > Templates
create RebateSettings as query param. (when creating contract u need to create rebate settings)
autoform
navigation implemantation

**Comment by a0m0rajab** [comment]
Add templates under management 
Crm do not use companies 
Show the left menu 
Rebate refund scenarios showing (preview)
Search for menu items and data items in navigation (bookmark Ertuğrul)
Add affiliations to CRM 
Local storage 
Change view to columns (visible columns)
Add sub companies to data grid as sub content 
Unexpected end of json (CRM)
Cookies - check and remove 
Headquarters 
Store 
Merchant 
Franchise 
Branch code 
Merchant 
Sub merchant 
Reporter 
Alert dialog for tables (have generic method)
Filter fetches 
change all languages in forms and dialogue to match the screen language 
add filters to all tables
